version: 2
checks:
  file-lines:
    config:
      threshold: 600
  method-lines:
    config:
      threshold: 50
  method-count:
    config:
      threshold: 50
exclude_patterns:
  - src/locale/**
  - __tests__/**
  - __mocks__/**
