name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          echo "${{ secrets.GA_CONTENTS }}" > "public/${{ secrets.GA_FILENAME }}"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: www.os-js.org
