name: Lint tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Lint tests (node latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run eslint
