name: CodeClimate Coverage
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  coverage:
    runs-on: ubuntu-latest
    name: CodeClimate Coverage
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm ci
    - uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: 6261ba4f6e5890c37688f390015831023481b8bedf53a2fec3e23695b6223513
      with:
        coverageCommand: npm run coverage
